<?php
	$form = $this->form;
?>
	
<div id="search_form" <?php if ($form->isErrors()) : ?> class="errors"<?php endif ?>>
		
	<form enctype="application/x-www-form-urlencoded" method="post" action="/mp/search/">
			
		<label for="searchField" id="searchFieldLabel">Search:</label>
		<input type="text" name="searchField" id="searchField" value="<?= $form->getElement('searchField')->getValue() ?>" />
		
		<?php if ($form->getElement('searchField')->hasErrors()) : ?>
			<p class="error">
				<?php 
					$errors = $form->getElement('searchField')->getErrorMessages();
					echo $errors[0];
				?>
			</p>
		<?php else : ?>
			<p class="info">Search by constituency name or full UK postcode<br /> e.g. "Ealing, Acton & Shepherd's Bush" or "W12 7RJ"</p>
		<?php endif ?>
				
		<input type="submit" name="Search" id="search" value="Search" />
		
	</form>

</div>